version: '3.8'

services:
  postgres-mission:
    image: postgres:15-alpine
    container_name: db_mission
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - mission_data:/var/lib/postgresql/data

volumes:
  mission_data: